name: Push docker image

on:
  push:
    branches:
      - main

jobs:
  build-run-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Copying code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            afalobaid9/go-app:latest
            afalobaid9/go-app:${{ github.sha }}
