name: Build go

on: [pull_request, push]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "^1.19"
        run: |
          go build
          go run hello.go
